# TCL File Generated by Component Editor 8.0sp1
# Mon Aug 18 10:06:49 EDT 2008
# DO NOT MODIFY


# +-----------------------------------
# | 
# | dummy_dut "dummy_dut" v1.0
# | RSF 2008.08.18.10:06:49
# | This component provides a sink and a source interface at the top level port map.
# | 
# +-----------------------------------


# +-----------------------------------
# | module dummy_dut
# | 
set_module_property DESCRIPTION "This component provides a sink and a source interface at the top level port map."
set_module_property NAME dummy_dut
set_module_property VERSION 1.0
set_module_property GROUP ""
set_module_property AUTHOR RSF
set_module_property DISPLAY_NAME dummy_dut
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE false
set_module_property SIMULATION_MODEL_IN_VERILOG false
set_module_property SIMULATION_MODEL_IN_VHDL false
set_module_property SIMULATION_MODEL_HAS_TULIPS false
set_module_property SIMULATION_MODEL_IS_OBFUSCATED false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock ptfSchematicName ""

add_interface_port clock clk clk Input 1
add_interface_port clock reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point in0
# | 
add_interface in0 avalon_streaming end
set_interface_property in0 maxChannel 0
set_interface_property in0 errorDescriptor ""
set_interface_property in0 readyLatency 0
set_interface_property in0 dataBitsPerSymbol 8
set_interface_property in0 symbolsPerBeat 2

set_interface_property in0 ASSOCIATED_CLOCK clock

add_interface_port in0 asi_in0_data data Input 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point out0
# | 
add_interface out0 avalon_streaming start
set_interface_property out0 maxChannel 0
set_interface_property out0 errorDescriptor ""
set_interface_property out0 readyLatency 0
set_interface_property out0 dataBitsPerSymbol 8
set_interface_property out0 symbolsPerBeat 2

set_interface_property out0 ASSOCIATED_CLOCK clock

add_interface_port out0 aso_out0_data data Output 16
# | 
# +-----------------------------------
