# TCL File Generated by Component Editor 8.0
# Wed Sep 10 13:13:19 PDT 2008
# DO NOT MODIFY


# +-----------------------------------
# | 
# | fmul "fmul" v1.0
# | null 2008.09.10.13:13:19
# | 
# | 
# | C:/_Embedded_Apps/_Designs_and_Code/Nios_II/MP3/NEEK/2008-08-27/mp3_player/ip/fixed_point_multiply/fmul.v
# | 
# |    ./fmul.v syn, sim
# |    ./mult.v syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module fmul
# | 
set_module_property NAME fmul
set_module_property VERSION 1.0
set_module_property GROUP ""
set_module_property DISPLAY_NAME fmul
set_module_property TOP_LEVEL_HDL_FILE fmul.v
set_module_property TOP_LEVEL_HDL_MODULE fmul
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property SIMULATION_MODEL_IN_VERILOG false
set_module_property SIMULATION_MODEL_IN_VHDL false
set_module_property SIMULATION_MODEL_HAS_TULIPS false
set_module_property SIMULATION_MODEL_IS_OBFUSCATED false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file fmul.v {SYNTHESIS SIMULATION}
add_file mult.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point nios_custom_instruction_slave_0
# | 
add_interface nios_custom_instruction_slave_0 nios_custom_instruction end
set_interface_property nios_custom_instruction_slave_0 operands 2
set_interface_property nios_custom_instruction_slave_0 clockCycle 0
set_interface_property nios_custom_instruction_slave_0 clockCycleType VARIABLE

add_interface_port nios_custom_instruction_slave_0 start start Input 1
add_interface_port nios_custom_instruction_slave_0 clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave_0 dataa dataa Input 32
add_interface_port nios_custom_instruction_slave_0 datab datab Input 32
add_interface_port nios_custom_instruction_slave_0 done done Output 1
add_interface_port nios_custom_instruction_slave_0 result result Output 32
add_interface_port nios_custom_instruction_slave_0 clk clk Input 1
add_interface_port nios_custom_instruction_slave_0 reset reset Input 1
# | 
# +-----------------------------------
