# TCL File Generated by Component Editor 8.0
# Tue Sep 16 09:22:00 PDT 2008
# DO NOT MODIFY


# +-----------------------------------
# | 
# | audio_codec_wm8731 "Audio Codec Controller WM8731" v8.0
# | Nate Knight 2008.09.16.09:22:00
# | 
# | 
# | C:/_Embedded_Apps/_Designs_and_Code/Nios_II/MP3/NEEK/audio_chip_component_test/ip/Audio_Codec_WM8731/audio_codec_wm8731.v
# | 
# |    ./audio_codec_wm8731.v syn
# |    ./avalon_regs_library.v syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module audio_codec_wm8731
# | 
set_module_property DESCRIPTION ""
set_module_property NAME audio_codec_wm8731
set_module_property VERSION 8.0
set_module_property GROUP Audio
set_module_property AUTHOR "Nate Knight"
set_module_property DISPLAY_NAME "Audio Codec Controller WM8731"
set_module_property TOP_LEVEL_HDL_FILE audio_codec_wm8731.v
set_module_property TOP_LEVEL_HDL_MODULE audio_codec_WM8731
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property SIMULATION_MODEL_IN_VERILOG false
set_module_property SIMULATION_MODEL_IN_VHDL false
set_module_property SIMULATION_MODEL_HAS_TULIPS false
set_module_property SIMULATION_MODEL_IS_OBFUSCATED false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file audio_codec_wm8731.v SYNTHESIS
add_file avalon_regs_library.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter DAC_FIFO_DEPTH int 1024
set_parameter_property DAC_FIFO_DEPTH DISPLAY_NAME DAC_FIFO_DEPTH
set_parameter_property DAC_FIFO_DEPTH UNITS None
set_parameter_property DAC_FIFO_DEPTH AFFECTS_PORT_WIDTHS true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point global_signals_clock
# | 
add_interface global_signals_clock clock end
set_interface_property global_signals_clock ptfSchematicName ""

add_interface_port global_signals_clock clk clk Input 1
add_interface_port global_signals_clock reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave minimumUninterruptedRunLength 1
set_interface_property avalon_slave bridgesToMaster ""
set_interface_property avalon_slave isMemoryDevice true
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave addressSpan 1024
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave writeWaitTime 1
set_interface_property avalon_slave writeWaitStates 1
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave addressAlignment DYNAMIC
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave printableDevice false

set_interface_property avalon_slave ASSOCIATED_CLOCK global_signals_clock

add_interface_port avalon_slave avalon_slave_address address Input 3
add_interface_port avalon_slave avalon_slave_readdata readdata Output 32
add_interface_port avalon_slave avalon_slave_writedata writedata Input 32
add_interface_port avalon_slave avalon_slave_write write Input 1
add_interface_port avalon_slave avalon_slave_read read Input 1
add_interface_port avalon_slave avalon_slave_chipselect chipselect Input 1
add_interface_port avalon_slave avalon_slave_byteenable byteenable Input 4
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_export
# | 
add_interface avalon_slave_export conduit start

set_interface_property avalon_slave_export ASSOCIATED_CLOCK global_signals_clock

add_interface_port avalon_slave_export xck export Output 1
add_interface_port avalon_slave_export bclk export Output 1
add_interface_port avalon_slave_export dacdat export Output 1
add_interface_port avalon_slave_export daclrck export Output 1
add_interface_port avalon_slave_export adcdat export Input 1
add_interface_port avalon_slave_export adclrck export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt_sender
# | 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave

set_interface_property interrupt_sender ASSOCIATED_CLOCK global_signals_clock

add_interface_port interrupt_sender avalon_slave_irq irq Output 1
# | 
# +-----------------------------------
