# TCL File Generated by Component Editor 8.0sp1
# Mon Aug 18 10:01:18 EDT 2008
# DO NOT MODIFY


# +-----------------------------------
# | 
# | dummy_build_id "dummy_build_id" v1.0
# | RSF 2008.08.18.10:01:18
# | This component provides a slave port at the top level to wire up a build ID.
# | 
# +-----------------------------------


# +-----------------------------------
# | module dummy_build_id
# | 
set_module_property DESCRIPTION "This component provides a slave port at the top level to wire up a build ID."
set_module_property NAME dummy_build_id
set_module_property VERSION 1.0
set_module_property GROUP ""
set_module_property AUTHOR RSF
set_module_property DISPLAY_NAME dummy_build_id
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE false
set_module_property SIMULATION_MODEL_IN_VERILOG false
set_module_property SIMULATION_MODEL_IN_VHDL false
set_module_property SIMULATION_MODEL_HAS_TULIPS false
set_module_property SIMULATION_MODEL_IS_OBFUSCATED false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock ptfSchematicName ""

add_interface_port clock clk clk Input 1
add_interface_port clock reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s0
# | 
add_interface s0 avalon end
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 minimumUninterruptedRunLength 1
set_interface_property s0 bridgesToMaster ""
set_interface_property s0 isMemoryDevice false
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 addressSpan 4
set_interface_property s0 timingUnits Cycles
set_interface_property s0 setupTime 0
set_interface_property s0 writeWaitTime 0
set_interface_property s0 isNonVolatileStorage false
set_interface_property s0 addressAlignment DYNAMIC
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 readLatency 0
set_interface_property s0 printableDevice false

set_interface_property s0 ASSOCIATED_CLOCK clock

add_interface_port s0 avs_s0_readdata readdata Output 32
# | 
# +-----------------------------------
