# TCL File Generated by Component Editor 7.2 on:
# Sat Dec 22 15:37:25 JST 2007
# DO NOT MODIFY

set_source_file "opencores_i2c_master.vhd"
set_module "opencores_i2c_master"
set_module_property NAME opencores_i2c_master
set_module_description ""
set_module_property "displayName" "OpenCores I2C Master"
set_module_property "editable" "true"
set_module_property "group" "Interface Protocols/I2C"
set_module_property "instantiateInSystemModule" "true"
set_module_property "synthesisFiles" [ list "opencores_i2c_master.vhd" "i2c_master_top.vhd" "i2c_master_byte_ctrl.vhd" "i2c_master_bit_ctrl.vhd"]
set_module_property "libraries" [ list "ieee.std_logic_1164.all" "ieee.std_logic_arith.all" "std.standard.all" ]
set_module_property "version" "1.0"

# Module parameters

# Interface avalon_slave_0_clock
add_interface "avalon_slave_0_clock" "clock" "sink" "asynchronous"
# Ports in interface avalon_slave_0_clock
add_port_to_interface "avalon_slave_0_clock" "wb_clk_i" "clk"
add_port_to_interface "avalon_slave_0_clock" "wb_rst_i" "reset"

# Interface global_signals_export
add_interface "global_signals_export" "conduit" "start" "asynchronous"
# Ports in interface global_signals_export
add_port_to_interface "global_signals_export" "scl_pad_io" "export"
add_port_to_interface "global_signals_export" "sda_pad_io" "export"

# Interface avalon_slave_0
add_interface "avalon_slave_0" "avalon" "slave" "avalon_slave_0_clock"
set_interface_property "avalon_slave_0" "isNonVolatileStorage" "false"
set_interface_property "avalon_slave_0" "burstOnBurstBoundariesOnly" "false"
set_interface_property "avalon_slave_0" "readLatency" "0"
set_interface_property "avalon_slave_0" "readWaitStates" "0"
set_interface_property "avalon_slave_0" "holdTime" "0"
set_interface_property "avalon_slave_0" "printableDevice" "false"
set_interface_property "avalon_slave_0" "readWaitTime" "0"
set_interface_property "avalon_slave_0" "setupTime" "0"
set_interface_property "avalon_slave_0" "addressAlignment" "DYNAMIC"
set_interface_property "avalon_slave_0" "writeWaitTime" "0"
set_interface_property "avalon_slave_0" "timingUnits" "Cycles"
set_interface_property "avalon_slave_0" "minimumUninterruptedRunLength" "1"
set_interface_property "avalon_slave_0" "isMemoryDevice" "true"
set_interface_property "avalon_slave_0" "linewrapBursts" "false"
set_interface_property "avalon_slave_0" "maximumPendingReadTransactions" "0"
# Ports in interface avalon_slave_0
add_port_to_interface "avalon_slave_0" "wb_ack_o" "waitrequest_n"
add_port_to_interface "avalon_slave_0" "wb_adr_i" "address"
add_port_to_interface "avalon_slave_0" "wb_cs_i" "chipselect"
add_port_to_interface "avalon_slave_0" "wb_dat_i" "writedata"
add_port_to_interface "avalon_slave_0" "wb_dat_o" "readdata"
add_port_to_interface "avalon_slave_0" "wb_we_i" "write"

# Interface avalon_slave_0_irq
add_interface "avalon_slave_0_irq" "interrupt" "sender" "avalon_slave_0_clock"
set_interface_property "avalon_slave_0_irq" "associatedAddressablePoint" "avalon_slave_0"
# Ports in interface avalon_slave_0_irq
add_port_to_interface "avalon_slave_0_irq" "wb_inta_o" "irq"

# Interface avalon_slave_0_export
add_interface "avalon_slave_0_export" "conduit" "start" "avalon_slave_0_clock"
# Ports in interface avalon_slave_0_export
add_port_to_interface "avalon_slave_0_export" "wb_err_o" "export"
